secret_key_base: "409B6B1796C275462A1703113804BB82D39DC0E3"
twilio_account_sid:  <%= ENV.fetch("TWILIO_ACCOUNT_SID", "ACefb69d85b304fafeb67f04eb617e8416") %>
twilio_auth_token:  <%= ENV.fetch("TWILIO_AUTH_TOKEN", "97eaf829884c41cd267a344dc143a655") %>
twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "+12512913707") %>